In [2]:
import numpy as np
import numpy.matlib as mat
import numpy.linalg as lin
from IPython import InteractiveShell
import matplotlib
from matplotlib import pyplot
InteractiveShell.ast_node_interactivity = 'all'
%matplotlib inline

### 11.2 Left and right inverses of a vector. 
Suppose that x is a nonzero n-vector with n > 1.
- Does x have a left inverse?
- Does x have a right inverse?
- If yes, give formula for inverse, if no, give a counterexample.


In [3]:
# Note that the identity of an n-vector is 1.
x = np.mat("1 2 3 4").T; x
print("Identity for an n-vector = ")
I = np.eye(1); I
print("Frobenius Norm =")
froNorm_sqrd = np.float64(x.T @ x); froNorm_sqrd
print("Left Inverse =")
ALeftInv = (x/froNorm_sqrd**2).T; ALeftInv
print("Proof: AleftInv @ x = ")
ALeftInv @ x
# For a right inverse, one cannot exist because the dimension of x is (n x 1) and there is no
# matrix or vector multiplication operation we can do on it to get a 1x1.

matrix([[1],
        [2],
        [3],
        [4]])

Identity for an n-vector = 


array([[1.]])

Frobenius Norm =


30.0

Left Inverse =


matrix([[0.00111111, 0.00222222, 0.00333333, 0.00444444]])

Proof: AleftInv @ x = 


matrix([[0.03333333]])

In [6]:
# Extra exploration 11.2
A = np.mat("-3 -4;4 6;1 1"); A
leftInv = lin.pinv(A); leftInv

matrix([[-3, -4],
        [ 4,  6],
        [ 1,  1]])

matrix([[-1.22222222, -1.11111111,  1.77777778],
        [ 0.77777778,  0.88888889, -1.22222222]])