In [1]:
import numpy as np
import numpy.matlib as mat
import numpy.linalg as lin
from IPython import InteractiveShell
import matplotlib
from matplotlib import pyplot
InteractiveShell.ast_node_interactivity = 'all'
%matplotlib inline


In [2]:
M = mat.mat("1 2 4;-1 2 1;0 1 0").reshape((3, 3))
M


matrix([[ 1,  2,  4],
        [-1,  2,  1],
        [ 0,  1,  0]])

In [3]:
type(M)
M.shape


numpy.matrix

(3, 3)

# Matrix inverses exist only if determinant != 0

In [4]:
lin.det(M)
assert(not np.isclose(lin.det(M), 0))
lin.inv(M)


-4.999999999999999

matrix([[ 0.2, -0.8,  1.2],
        [ 0. ,  0. ,  1. ],
        [ 0.2,  0.2, -0.8]])

In [5]:
# Demonstrate inversion worked
np.isclose(M @ lin.inv(M), mat.eye(3, 3))
# Matrix times its inverse ==  inverse times the matrix
np.isclose(lin.inv(M) @ M, mat.eye(3, 3))


matrix([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])

matrix([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])

In [6]:
# Shape of a single dimension matrix
v_single_dim = mat.mat("1 2 3")
v_single_dim
v_single_dim.shape


matrix([[1, 2, 3]])

(1, 3)

In [7]:
# Shape of a single dimension array
a_single_dim = np.array([1, 2, 3])
a_single_dim
a_single_dim.shape


array([1, 2, 3])

(3,)

In [8]:
# Convert 1d array to matrix to correct the shape
v = np.mat(np.array([1, 2, 3]))
v = v.transpose()
v.shape


(3, 1)

In [9]:
# Element-wise addition and multiplication
v
v * 3
v + 2


matrix([[1],
        [2],
        [3]])

matrix([[3],
        [6],
        [9]])

matrix([[3],
        [4],
        [5]])

# Inner product amd Cross Product

In [10]:
v.transpose()@v  # inner product of a vector is a scalar
v@v.transpose()  # v v^T  of a vector is a matrix


matrix([[14]])

matrix([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [11]:
w = np.mat("0.5;-1;1")
w
v
np.cross(w.transpose(), v.transpose())


matrix([[ 0.5],
        [-1. ],
        [ 1. ]])

matrix([[1],
        [2],
        [3]])

array([[-5. , -0.5,  2. ]])

In [12]:
np.cross(np.mat([1, -1]), np.mat([-1, 1]))  # 2D cross product is single number
# 3D cross product is a vector
np.cross(np.mat([1, -1, 3]), np.mat([3, -1, 1]))
# Cross product operation is ONLY defined for 2- and 3-vectors


array([0])

array([[2, 8, 2]])

# Eigenvalues and Eigenvectors
$A u = \lambda  u$    
where $A \in R^{n,n}$.  
$u$ is eigenvector   
$\lambda$ is eigenvalue
   
This can be thought of as "multiplying by u scales A by lambda".  


Rearranging top equation, it has a solution if and only if $det(A-\lambda I) = 0$   
The eigenvalues are the roots of this determinant, which is a polynomial in $\lambda$.

In [15]:
def get_matrix_and_eigenvals_and_eigenvecs():
    np.set_printoptions(precision=3, suppress=True)
    count = 0
    for i in range(10000):
        _m = np.round(mat.mat(np.random.randint(
            1, 10, size=9)).reshape(3, 3)*1)
        if np.isclose(lin.det(_m), 0.0):
            count += 1
            lam, u = lin.eig(_m)
            print("matrix".center(20,"-"))
            print(_m)
            print("eigenvecs".center(20,"-"))
            print(u)
            print("eigenvals".center(20,"-"))
            print(lam)
            print("-"*20)
            return lam, u, _m


In [16]:
lams, us, A = get_matrix_and_eigenvals_and_eigenvecs()
# check eigenvalues and eigenvectors
np.set_printoptions(precision=2)
for i in range(len(lams)):
    lam, u = lams[i], us[:,i]
    print("shapes:", A.shape, u.shape)
    print("--"*20)
    print("A @ u         ===     lam * u")
    print("--"*20)
    print("LHS:")
    print(A.dot(u))
    print("RHS:")
    print(u * lam)
    print("--"*20)


-------matrix-------
[[6 2 2]
 [3 1 2]
 [9 3 8]]
-----eigenvecs------
[[ 0.358  0.53   0.316]
 [ 0.251 -0.063 -0.949]
 [ 0.899 -0.845  0.   ]]
-----eigenvals------
[12.424  2.576 -0.   ]
--------------------
shapes: (3, 3) (3, 1)
----------------------------------------
A @ u         ===     lam * u
----------------------------------------
LHS:
[[ 4.45]
 [ 3.12]
 [11.17]]
RHS:
[[ 4.45]
 [ 3.12]
 [11.17]]
----------------------------------------
shapes: (3, 3) (3, 1)
----------------------------------------
A @ u         ===     lam * u
----------------------------------------
LHS:
[[ 1.37]
 [-0.16]
 [-2.18]]
RHS:
[[ 1.37]
 [-0.16]
 [-2.18]]
----------------------------------------
shapes: (3, 3) (3, 1)
----------------------------------------
A @ u         ===     lam * u
----------------------------------------
LHS:
[[-0.]
 [-0.]
 [-0.]]
RHS:
[[-0.]
 [ 0.]
 [ 0.]]
----------------------------------------


# Singular Value Decomposition (SVD)
- Decompose a matrix into 3 matrices

In [17]:
U, S, Vtranspose = np.linalg.svd(A)
U, S, Vtranspose

(matrix([[-0.44,  0.88,  0.19],
         [-0.26,  0.08, -0.96],
         [-0.86, -0.47,  0.19]]),
 array([14.38,  2.29,  0.  ]),
 matrix([[-0.78, -0.26, -0.58],
         [ 0.55,  0.18, -0.82],
         [ 0.32, -0.95, -0.  ]]))

In [18]:
# Pseudo Inverse
B= np.mat("1 0;-1 0")
Bpseudo = lin.pinv(B)
Bpseudo


matrix([[ 0.5, -0.5],
        [ 0. ,  0. ]])

In [19]:
# demonstrate B and Bpseudo
B @ Bpseudo
Bpseudo @ B
B.T @ (B@B.T).__invert__()

matrix([[ 0.5, -0.5],
        [-0.5,  0.5]])

matrix([[1., 0.],
        [0., 0.]])

matrix([[-2,  2],
        [ 0,  0]])

In [20]:
# Demonstrate pseudo inverse for solving over-determined system of linear equations
A = np.mat("-3 -4;4 6;1 1")
b = np.mat("1;-2;0")
q,r = lin.qr(A)
q
r

matrix([[-0.59, -0.46],
        [ 0.78, -0.52],
        [ 0.2 ,  0.72]])

matrix([[ 5.1 ,  7.26],
        [ 0.  , -0.59]])

In [21]:
Apseudo = lin.inv(r) @ q.T
Apseudo

matrix([[-1.22, -1.11,  1.78],
        [ 0.78,  0.89, -1.22]])

In [22]:
x = Apseudo.dot(b)
x

matrix([[ 1.],
        [-1.]])

In [23]:
A.dot(x)

matrix([[ 1.],
        [-2.],
        [-0.]])